# Generated by Django 5.0.3 on 2024-04-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='unique_id',
        ),
    ]
