# Generated by Django 5.0.3 on 2024-04-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_exercise_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.CharField(default='descriptionnn', max_length=255),
        ),
    ]
